# Generated by Django 4.2.16 on 2024-09-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vouchers",
            new_name="Voucher",
        ),
    ]
